sonar.organization=gradion
sonar.projectKey=gradionai_acdc-poc
sonar.sources=server/src,web/src
sonar.tests=server/test,web/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info,web/coverage/lcov.info
sonar.exclusions=**/dist/**,e2e/**,**/*.config.*,web/src/main.tsx
