name: Add to project
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/gradionai/projects/7
          github-token: ${{ secrets.PROJECTS_TOKEN }}
